# Generated by Django 3.1.2 on 2020-11-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDetails',
            fields=[
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('liked_urls', models.ManyToManyField(to='recommend.UrlDetails')),
            ],
        ),
    ]
