# Generated by Django 3.1.2 on 2020-11-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urldetails',
            options={'ordering': ['url', 'title', 'uid']},
        ),
    ]
